
package infatlan.hn.srvbasa010.servicios.expuestos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import infatlan.hn.srvbasa010.interfaces.ObjectFactory;
import infatlan.hn.srvbasa010.interfaces.PeticionSrvBasa010;
import infatlan.hn.srvbasa010.interfaces.RespuestaSrvBasa010;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioSrvBasa010Interfaz", targetNamespace = "http://interfaces.srvbasa010.hn.infatlan/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioSrvBasa010Interfaz {


    /**
     * 
     * @param peticionSrvBasa010
     * @return
     *     returns infatlan.hn.srvbasa010.interfaces.RespuestaSrvBasa010
     */
    @WebMethod
    @WebResult(name = "RespuestaSrvBasa010", targetNamespace = "")
    @RequestWrapper(localName = "ejecutarSrvBasa010", targetNamespace = "http://interfaces.srvbasa010.hn.infatlan/", className = "infatlan.hn.srvbasa010.interfaces.EjecutarSrvBasa010")
    @ResponseWrapper(localName = "ejecutarSrvBasa010Response", targetNamespace = "http://interfaces.srvbasa010.hn.infatlan/", className = "infatlan.hn.srvbasa010.interfaces.EjecutarSrvBasa010Response")
    public RespuestaSrvBasa010 ejecutarSrvBasa010(
        @WebParam(name = "PeticionSrvBasa010", targetNamespace = "")
        PeticionSrvBasa010 peticionSrvBasa010);

}
