
package infatlan.hn.srvbasa010.servicios.expuestos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SrvBasa010ServiceService", targetNamespace = "http://expuestos.servicios.srvbasa010.hn.infatlan/", wsdlLocation = "http://srvbasa.bancatlan.hn:30010/SRVBASA010-1.0/ServicioSrvBasa010Interfaz?wsdl")
public class SrvBasa010ServiceService
    extends Service
{

    private final static URL SRVBASA010SERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SRVBASA010SERVICESERVICE_EXCEPTION;
    private final static QName SRVBASA010SERVICESERVICE_QNAME = new QName("http://expuestos.servicios.srvbasa010.hn.infatlan/", "SrvBasa010ServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://srvbasa.bancatlan.hn:30010/SRVBASA010-1.0/ServicioSrvBasa010Interfaz?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRVBASA010SERVICESERVICE_WSDL_LOCATION = url;
        SRVBASA010SERVICESERVICE_EXCEPTION = e;
    }

    public SrvBasa010ServiceService() {
        super(__getWsdlLocation(), SRVBASA010SERVICESERVICE_QNAME);
    }

    public SrvBasa010ServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRVBASA010SERVICESERVICE_QNAME, features);
    }

    public SrvBasa010ServiceService(URL wsdlLocation) {
        super(wsdlLocation, SRVBASA010SERVICESERVICE_QNAME);
    }

    public SrvBasa010ServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRVBASA010SERVICESERVICE_QNAME, features);
    }

    public SrvBasa010ServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrvBasa010ServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioSrvBasa010Interfaz
     */
    @WebEndpoint(name = "SrvBasa010ServicePort")
    public ServicioSrvBasa010Interfaz getSrvBasa010ServicePort() {
        return super.getPort(new QName("http://expuestos.servicios.srvbasa010.hn.infatlan/", "SrvBasa010ServicePort"), ServicioSrvBasa010Interfaz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioSrvBasa010Interfaz
     */
    @WebEndpoint(name = "SrvBasa010ServicePort")
    public ServicioSrvBasa010Interfaz getSrvBasa010ServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://expuestos.servicios.srvbasa010.hn.infatlan/", "SrvBasa010ServicePort"), ServicioSrvBasa010Interfaz.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRVBASA010SERVICESERVICE_EXCEPTION!= null) {
            throw SRVBASA010SERVICESERVICE_EXCEPTION;
        }
        return SRVBASA010SERVICESERVICE_WSDL_LOCATION;
    }

}
