
package infatlan.hn.srvbasa006.servicios.expuestos;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import infatlan.hn.srvbasa006.interfaces.ObjectFactory;
import infatlan.hn.srvbasa006.interfaces.PeticionSrvBasa006;
import infatlan.hn.srvbasa006.interfaces.RespuestaSrvBasa006;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServicioSrvBasa006Interfaz", targetNamespace = "http://interfaces.srvbasa006.hn.infatlan/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServicioSrvBasa006Interfaz {


    /**
     * 
     * @param peticionSrvBasa006
     * @return
     *     returns infatlan.hn.srvbasa006.interfaces.RespuestaSrvBasa006
     */
    @WebMethod
    @WebResult(name = "RespuestaSrvBasa006", targetNamespace = "")
    @RequestWrapper(localName = "ejecutarSrvBasa006", targetNamespace = "http://interfaces.srvbasa006.hn.infatlan/", className = "infatlan.hn.srvbasa006.interfaces.EjecutarSrvBasa006")
    @ResponseWrapper(localName = "ejecutarSrvBasa006Response", targetNamespace = "http://interfaces.srvbasa006.hn.infatlan/", className = "infatlan.hn.srvbasa006.interfaces.EjecutarSrvBasa006Response")
    public RespuestaSrvBasa006 ejecutarSrvBasa006(
        @WebParam(name = "PeticionSrvBasa006", targetNamespace = "")
        PeticionSrvBasa006 peticionSrvBasa006);

}
