
package infatlan.hn.srvbasa006.servicios.expuestos;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SrvBasa006ServiceService", targetNamespace = "http://expuestos.servicios.srvbasa006.hn.infatlan/", wsdlLocation = "http://srvbasa.bancatlan.hn:30006/SRVBASA006-1.0/ServicioSrvBasa006Interfaz?wsdl")
public class SrvBasa006ServiceService
    extends Service
{

    private final static URL SRVBASA006SERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException SRVBASA006SERVICESERVICE_EXCEPTION;
    private final static QName SRVBASA006SERVICESERVICE_QNAME = new QName("http://expuestos.servicios.srvbasa006.hn.infatlan/", "SrvBasa006ServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://srvbasa.bancatlan.hn:30006/SRVBASA006-1.0/ServicioSrvBasa006Interfaz?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SRVBASA006SERVICESERVICE_WSDL_LOCATION = url;
        SRVBASA006SERVICESERVICE_EXCEPTION = e;
    }

    public SrvBasa006ServiceService() {
        super(__getWsdlLocation(), SRVBASA006SERVICESERVICE_QNAME);
    }

    public SrvBasa006ServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SRVBASA006SERVICESERVICE_QNAME, features);
    }

    public SrvBasa006ServiceService(URL wsdlLocation) {
        super(wsdlLocation, SRVBASA006SERVICESERVICE_QNAME);
    }

    public SrvBasa006ServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SRVBASA006SERVICESERVICE_QNAME, features);
    }

    public SrvBasa006ServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SrvBasa006ServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioSrvBasa006Interfaz
     */
    @WebEndpoint(name = "SrvBasa006ServicePort")
    public ServicioSrvBasa006Interfaz getSrvBasa006ServicePort() {
        return super.getPort(new QName("http://expuestos.servicios.srvbasa006.hn.infatlan/", "SrvBasa006ServicePort"), ServicioSrvBasa006Interfaz.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioSrvBasa006Interfaz
     */
    @WebEndpoint(name = "SrvBasa006ServicePort")
    public ServicioSrvBasa006Interfaz getSrvBasa006ServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://expuestos.servicios.srvbasa006.hn.infatlan/", "SrvBasa006ServicePort"), ServicioSrvBasa006Interfaz.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SRVBASA006SERVICESERVICE_EXCEPTION!= null) {
            throw SRVBASA006SERVICESERVICE_EXCEPTION;
        }
        return SRVBASA006SERVICESERVICE_WSDL_LOCATION;
    }

}
